name: My Workflow
on: push

jobs:
  my-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: |
          echo "first multi line command"
          echo "second multi line command"
      - name: My second step
        run: echo "hello second step"
      - name: Get code
        uses: actions/checkout@v3
      - name: List files
        run: ls
        