name: My Workflow
on: workflow_dispatch

jobs:
  my-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: |
          echo "first multi line command"
          echo "second multi line command"
      - name: My second step
        run: echo "hello second step"