# compulsory name of workflow
name: My Workflow
# manual workflow
on: workflow_dispatch

jobs:
  my-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: echo "hello first step"
      - name: My second step
        run: echo "hello second step"